/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastas.UI;

/**
 *
 * @author Xelop
 */
public class AgentMenu extends javax.swing.JFrame {

    /**
     * Creates new form AgentMenu
     */
    public AgentMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Agent = new javax.swing.JLabel();
        _btnl_Register = new javax.swing.JButton();
        _btn_CreditCard = new javax.swing.JButton();
        _lbl_ModifyParticipant = new javax.swing.JButton();
        _btn_SuspendParticipant = new javax.swing.JButton();
        _btn_ActivateParticipant = new javax.swing.JButton();
        _btn_More = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Agent.setText("AGENT");

        _btnl_Register.setText("Register Participants");
        _btnl_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnl_RegisterActionPerformed(evt);
            }
        });

        _btn_CreditCard.setText("Include Credit Card");
        _btn_CreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_CreditCardActionPerformed(evt);
            }
        });

        _lbl_ModifyParticipant.setText("Modify Participant");
        _lbl_ModifyParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _lbl_ModifyParticipantActionPerformed(evt);
            }
        });

        _btn_SuspendParticipant.setText("Suspend Participant");
        _btn_SuspendParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_SuspendParticipantActionPerformed(evt);
            }
        });

        _btn_ActivateParticipant.setText("Activate Participant");
        _btn_ActivateParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_ActivateParticipantActionPerformed(evt);
            }
        });

        _btn_More.setText("More");
        _btn_More.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_MoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(_lbl_Agent))
                    .addComponent(_btnl_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_btn_CreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lbl_ModifyParticipant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_btn_SuspendParticipant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_btn_ActivateParticipant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_btn_More, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(_lbl_Agent)
                .addGap(31, 31, 31)
                .addComponent(_btnl_Register)
                .addGap(18, 18, 18)
                .addComponent(_btn_CreditCard)
                .addGap(18, 18, 18)
                .addComponent(_lbl_ModifyParticipant)
                .addGap(18, 18, 18)
                .addComponent(_btn_SuspendParticipant)
                .addGap(18, 18, 18)
                .addComponent(_btn_ActivateParticipant)
                .addGap(18, 18, 18)
                .addComponent(_btn_More)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnl_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnl_RegisterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AttributesUser(this,3,0).setVisible(true);
    }//GEN-LAST:event__btnl_RegisterActionPerformed

    private void _btn_CreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_CreditCardActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateCardParticipant(this).setVisible(true);
    }//GEN-LAST:event__btn_CreditCardActionPerformed

    private void _lbl_ModifyParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__lbl_ModifyParticipantActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GetIdentification(this, 2).setVisible(true);
    }//GEN-LAST:event__lbl_ModifyParticipantActionPerformed

    private void _btn_SuspendParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_SuspendParticipantActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StateUser(this, 3).setVisible(true);
    }//GEN-LAST:event__btn_SuspendParticipantActionPerformed

    private void _btn_ActivateParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_ActivateParticipantActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StateUser(this, 4).setVisible(true);
    }//GEN-LAST:event__btn_ActivateParticipantActionPerformed

    private void _btn_MoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_MoreActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuAll(this).setVisible(true);
    }//GEN-LAST:event__btn_MoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_ActivateParticipant;
    private javax.swing.JButton _btn_CreditCard;
    private javax.swing.JButton _btn_More;
    private javax.swing.JButton _btn_SuspendParticipant;
    private javax.swing.JButton _btnl_Register;
    private javax.swing.JLabel _lbl_Agent;
    private javax.swing.JButton _lbl_ModifyParticipant;
    // End of variables declaration//GEN-END:variables
}
