/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastas.UI;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import subastas.Logic.DataBaseConnection;
import subastas.Logic.HashTextTest;

/**
 *
 * @author Xelop
 */
public class AttributesUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateAgent
     */
    JFrame _Previuos;
    int _Action;
    int _Identification;
    ArrayList<String> _Telephones;
    DataBaseConnection _Connection = DataBaseConnection.getInstance();
    
    public AttributesUser(JFrame pPreviuos, int pAction, int pIdentification) { // 1 = modify, 2 = create agent,
                                                                                //3 = create participant 4= modify participant
        initComponents();
        _Previuos = pPreviuos;
        _Action=pAction;
        _Identification = pIdentification;
        _Telephones =new ArrayList<String>();
        _Jlst_Telephone_Numbers.setListData(_Telephones.toArray());
        if(_Action == 1){
            this._lbl_Action.setText("MODIFY AGENT");
            this._lbl_Identification.setVisible(false);
            this._txt_Identification.setVisible(false);
            this._txt_Credit.setVisible(false);
            this._lbl_Credit.setVisible(false);
            this._lbl_Email.setVisible(false);
            this._txt_Email.setVisible(false);
        }else if(_Action == 2){
            this._lbl_Action.setText("CREATE AGENT");
            this._txt_Credit.setVisible(false);
            this._lbl_Credit.setVisible(false);
            this._lbl_Email.setVisible(false);
            this._txt_Email.setVisible(false);
        }else if(_Action == 3){
            this._lbl_Action.setText("CREATE PARTICIPANT");
        }else if( _Action == 4){
            this._lbl_Action.setText("MODIFY PARTICIPANT");
            this._lbl_Identification.setVisible(false);
            this._txt_Identification.setVisible(false);
            this._txt_Credit.setVisible(false);
            this._lbl_Credit.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Action = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        _txt_Identification = new javax.swing.JTextField();
        _txt_Alias = new javax.swing.JTextField();
        _txt_Name = new javax.swing.JTextField();
        _txt_LastName1 = new javax.swing.JTextField();
        _txt_LastName2 = new javax.swing.JTextField();
        _txt_Password = new javax.swing.JTextField();
        _lbl_Identification = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _lbl_Credit = new javax.swing.JLabel();
        _txt_Credit = new javax.swing.JTextField();
        _lbl_Email = new javax.swing.JLabel();
        _txt_Email = new javax.swing.JTextField();
        _lbl_Credit1 = new javax.swing.JLabel();
        _txt_Address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        _Jlst_Telephone_Numbers = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        _txt_NewTelephone = new javax.swing.JTextField();
        _btn_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Action.setText("CREATE AGENT");

        _txt_Identification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _txt_IdentificationActionPerformed(evt);
            }
        });
        _txt_Identification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_IdentificationKeyReleased(evt);
            }
        });

        _lbl_Identification.setText("Identification:");

        jLabel1.setText("Alias: ");

        jLabel2.setText("Name: ");

        jLabel3.setText("First LastName: ");

        jLabel4.setText("Second LastName: ");

        jLabel5.setText("Password:");

        _lbl_Credit.setText("CreditCard Number: ");

        _txt_Credit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_CreditKeyReleased(evt);
            }
        });

        _lbl_Email.setText("Email");

        _lbl_Credit1.setText("Address");

        _txt_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_AddressKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lbl_Identification)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(_lbl_Email)
                    .addComponent(_lbl_Credit)
                    .addComponent(_lbl_Credit1))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_txt_Alias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_txt_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_txt_LastName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_txt_LastName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_txt_Identification, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_txt_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_lbl_Identification)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_txt_Identification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_txt_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(_txt_LastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_txt_LastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(_txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lbl_Email)
                    .addComponent(_txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_txt_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lbl_Credit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_Credit1)
                    .addComponent(_txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(_Jlst_Telephone_Numbers);

        jLabel6.setText("New Telephone : ");

        _txt_NewTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _txt_NewTelephoneActionPerformed(evt);
            }
        });
        _txt_NewTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_NewTelephoneKeyReleased(evt);
            }
        });

        _btn_Add.setText("ADD");
        _btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(_lbl_Action))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(_txt_NewTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(_btn_Add)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lbl_Action)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(_txt_NewTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btn_Add)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this._txt_Alias.getText().isEmpty()||(this._txt_Alias.getText().length() > 8&&this._txt_Alias.getText().length() < 15)){


            boolean error = false;
            if(_Action == 1){ //modify
                String[] values = new String[6];
                values[0] = this._txt_Alias.getText();
                values[1] = this._txt_Password.getText();
                values[2] = this._txt_Name.getText();
                values[3] = this._txt_LastName1.getText();
                values[4] = this._txt_LastName2.getText();
                values[5] = this._txt_Address.getText();

                for(int counter = 0; counter < 6; counter++){
                    if(values[counter].isEmpty()){
                        values[counter]=null;
                    }
                }
                if(values[1] != null){
                    values[1] = HashTextTest.sha2(this._txt_Password.getText());
                }
                error =_Connection.modifyAgent(this._Identification , values[0], values[1], values[2], values[3],
                        values[4], values[5]);

            }else if(_Action == 2){//create agent
                error =_Connection.createAgent(Integer.parseInt(this._txt_Identification.getText()), this._txt_Alias.getText()
                        ,HashTextTest.sha2(this._txt_Password.getText()), this._txt_Name.getText(), this._txt_LastName1.getText()
                        ,this._txt_LastName2.getText(), this._txt_Address.getText());

            }else if(_Action == 3){ 

                String credit= this._txt_Credit.getText();
                if(credit.isEmpty())
                    credit=null;
                error =_Connection.createParticipant(Integer.parseInt(this._txt_Identification.getText()), this._txt_Alias.getText()
                        , HashTextTest.sha2(this._txt_Password.getText()), this._txt_Name.getText(), this._txt_LastName1.getText()
                        ,this._txt_LastName2.getText(), credit, this._txt_Email.getText(), this._txt_Address.getText());
            }else if(_Action == 4){
                String[] values = new String[7];
                values[0] = this._txt_Alias.getText();
                values[1] = this._txt_Password.getText();
                values[2] = this._txt_Name.getText();
                values[3] = this._txt_LastName1.getText();
                values[4] = this._txt_LastName2.getText();
                values[5] = this._txt_Email.getText();
                values[6] = this._txt_Address.getText();

                for(int counter = 0; counter < 7; counter++){
                    if(values[counter].isEmpty()){
                        values[counter]=null;
                    }
                }
                if(values[1] != null){
                    values[1] = HashTextTest.sha2(this._txt_Password.getText());
                }
                error =_Connection.modifyParticipant(this._Identification , values[0], values[1], values[2], values[3],
                        values[4], values[5], values[6]);
            }
            if(!error){
                if(!_Telephones.isEmpty()){
                    _Connection.insertTelephones(Integer.parseInt(this._txt_Identification.getText()), _Telephones);
                }
            _Previuos.setVisible(true);
            this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Password or Alias muts be between 8 and 15 characters");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this._Previuos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void _btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_AddActionPerformed
        // TODO add your handling code here:
        _Telephones.add(_txt_NewTelephone.getText());
        _Jlst_Telephone_Numbers.setListData(_Telephones.toArray());
        _txt_NewTelephone.setText("");
    }//GEN-LAST:event__btn_AddActionPerformed

    private void _txt_IdentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__txt_IdentificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__txt_IdentificationActionPerformed

    private void _txt_IdentificationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_IdentificationKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else
            _txt_Identification.setText(""+_txt_Identification.getText().substring(0, _txt_Identification.getText().length() - 1));
    }//GEN-LAST:event__txt_IdentificationKeyReleased

    private void _txt_CreditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_CreditKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else
            _txt_Credit.setText(""+_txt_Credit.getText().substring(0, _txt_Credit.getText().length() - 1));
    }//GEN-LAST:event__txt_CreditKeyReleased

    private void _txt_NewTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__txt_NewTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__txt_NewTelephoneActionPerformed

    private void _txt_NewTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_NewTelephoneKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else
            _txt_NewTelephone.setText(""+_txt_NewTelephone.getText().substring(0, _txt_NewTelephone.getText().length() - 1));
    }//GEN-LAST:event__txt_NewTelephoneKeyReleased

    private void _txt_AddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_AddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event__txt_AddressKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttributesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttributesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttributesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttributesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AttributesAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList _Jlst_Telephone_Numbers;
    private javax.swing.JButton _btn_Add;
    private javax.swing.JLabel _lbl_Action;
    private javax.swing.JLabel _lbl_Credit;
    private javax.swing.JLabel _lbl_Credit1;
    private javax.swing.JLabel _lbl_Email;
    private javax.swing.JLabel _lbl_Identification;
    private javax.swing.JTextField _txt_Address;
    private javax.swing.JTextField _txt_Alias;
    private javax.swing.JTextField _txt_Credit;
    private javax.swing.JTextField _txt_Email;
    private javax.swing.JTextField _txt_Identification;
    private javax.swing.JTextField _txt_LastName1;
    private javax.swing.JTextField _txt_LastName2;
    private javax.swing.JTextField _txt_Name;
    private javax.swing.JTextField _txt_NewTelephone;
    private javax.swing.JTextField _txt_Password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
