/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastas.UI;

import java.util.Arrays;
import javax.swing.JFrame;
import subastas.Logic.DataBaseConnection;

/**
 *
 * @author Xelop
 */
public class ListInactiveAuctions extends javax.swing.JFrame {

    /**
     * Creates new form ListSubastas
     */
    DataBaseConnection _Connection;
    JFrame _Previous;
    String[] _ItemNames;
    Integer[] _AuctionId;
    String[] _ItemDescription;
    int _Action;
    
    public ListInactiveAuctions(JFrame pPrevious, int pAction, String pCategory, String pSubCategory, int pId){ // 1:Inactive, 2:Bids
                                                                                                       //3:list, 4:bids per auction
                                                                                                       // 5: auctions user
                                                                                                       //6: won 7:bought 8:sold
        initComponents();
        _Connection = DataBaseConnection.getInstance();
        _Action = pAction;
        if(_Action==1){
            Object[] x = _Connection.listSubastasInactivas();
            _ItemNames = (String[]) x[0];
            _AuctionId = (Integer[]) x[1];
            _lst_Auctions.setListData(_ItemNames);
        }else if(_Action == 2){
            _lbl_Action.setText("AUCTIONS");
            Object[] x = _Connection.listSubastasCategory(pCategory, pSubCategory);
            _ItemNames = (String[]) x[0];
            _AuctionId = (Integer[]) x[1];
            _ItemDescription = (String[]) x[2];
            _lst_Auctions.setListData(_ItemNames);
            jButton1.setText("Bid");
        }else if(_Action == 3){
            _lbl_Action.setText("AUCTIONS");
            jButton1.setVisible(false);
            Object[] x = _Connection.listSubastasCategory(pCategory, pSubCategory);
            _ItemNames = (String[]) x[0];
            _AuctionId = (Integer[]) x[1];
            _ItemDescription = (String[]) x[2];
            _lst_Auctions.setListData(_ItemNames);
        }else if(_Action == 4){
            _lbl_Action.setText("BIDS");
            jButton1.setVisible(false);
            _ItemNames = _Connection.bidsPerAuction(pId);
            _lst_Auctions.setListData(_ItemNames);
        }else if(_Action == 5){
            _lbl_Action.setText("AUCTIONS");
            jButton1.setVisible(false);
            _ItemNames = _Connection.auctionsPerUser(pCategory);
            _lst_Auctions.setListData(_ItemNames);
        }else if(_Action == 6){
            _lbl_Action.setText("WON AUCTIONS");
            jButton1.setVisible(false);
            _ItemNames = _Connection.wonAuctionsPerUser(pCategory);
            _lst_Auctions.setListData(_ItemNames);
        }else if(_Action == 7){
            _lbl_Action.setText("BOUGHT AUCTIONS");
            jButton1.setText("Add Comment");
            Object[] x = _Connection.listBought();
            _ItemNames = (String[]) x[0];
            _AuctionId = (Integer[]) x[1];
            _lst_Auctions.setListData(_ItemNames);
        }else if(_Action == 8){
            _lbl_Action.setText("SOLD AUCTIONS");
            jButton1.setText("Add Comment");
            Object[] x = _Connection.listSold();
            _ItemNames = (String[]) x[0];
            _AuctionId = (Integer[]) x[1];
            _lst_Auctions.setListData(_ItemNames);
        }
        _Previous = pPrevious;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Action = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _lst_Auctions = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Action.setText("RESTART AUCTIONS");

        jScrollPane1.setViewportView(_lst_Auctions);

        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(_lbl_Action))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lbl_Action)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(_Action == 1){
            int index = this._lst_Auctions.getSelectedIndex();
            new CreateAuction(_Previous, 2, _AuctionId[index]).setVisible(true);
            this.dispose();
        }else if(_Action == 2){
            int index = this._lst_Auctions.getSelectedIndex();
            new MakeBid(_Previous, _AuctionId[index],_ItemDescription[index]).setVisible(true);
            this.dispose();
        }else if( _Action == 7){
            int index = this._lst_Auctions.getSelectedIndex();
            new Comments(_Previous, 1, _AuctionId[index]).setVisible(true);
            this.dispose();
        }else if (_Action == 8){
            int index = this._lst_Auctions.getSelectedIndex();
            new Comments(_Previous, 2, _AuctionId[index]).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this._Previous.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListInactiveAuctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListInactiveAuctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListInactiveAuctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListInactiveAuctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListSubastas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lbl_Action;
    private javax.swing.JList _lst_Auctions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
