/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastas.UI;

import javax.swing.JOptionPane;
import subastas.Logic.DataBaseConnection;
import subastas.Logic.HashTextTest;

/**
 *
 * @author Xelop
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Username = new javax.swing.JLabel();
        _lbl_Password = new javax.swing.JLabel();
        _txt_Username = new javax.swing.JTextField();
        _txt_Password = new javax.swing.JTextField();
        _btn_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        _chk_administration = new javax.swing.JCheckBox();
        _chk_agent = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Username.setText("Username: ");

        _lbl_Password.setText("Password:");

        _btn_Login.setText("Login");
        _btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("CASA DE SUBASTAS");

        _chk_administration.setText(" Administrator");

        _chk_agent.setText("Agent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_lbl_Username)
                                    .addComponent(_lbl_Password))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(_chk_administration)
                            .addComponent(_chk_agent)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(_btn_Login)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lbl_Username)
                    .addComponent(_txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_Password)
                    .addComponent(_txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btn_Login)
                    .addComponent(_chk_administration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_chk_agent)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_LoginActionPerformed
        // TODO add your handling code here:
        DataBaseConnection connection = DataBaseConnection.getInstance();
        boolean error;
        if(_chk_administration.isSelected())
            error=connection.setConnection(_txt_Username.getText(),_txt_Password.getText());
        else if(_chk_agent.isSelected()){
            System.out.println(HashTextTest.sha2(_txt_Password.getText()));
            error=connection.setConnection(_txt_Username.getText(),HashTextTest.sha2(_txt_Password.getText()));
            
        }else
            error=connection.setConnection("participante","participante");
        
        if(!error){
            int type = connection.getUser(_txt_Username.getText());
            if(type == -5 &&_chk_agent.isSelected()){
                if(connection.isSuspendido()){
                    JOptionPane.showMessageDialog(null, "El usuario esta suspendido");
                }else{
                new AgentMenu().setVisible(true);
                this.dispose();
                }
            }else if(type == -6 &&_chk_administration.isSelected()){
                new AdministratorMenu().setVisible(true);
                this.dispose();
            }else if(type == -7){
                if(connection.verifyPassword(_txt_Username.getText(), _txt_Password.getText())){
                    if(connection.isSuspendido()){
                    JOptionPane.showMessageDialog(null, "El usuario esta suspendido");
                }else{
                    new ParticipantsMenu().setVisible(true);
                    this.dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Incorrect Password");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Verifique sus opciones seleccionadas");
                connection.setcon();
            }
        }
    }//GEN-LAST:event__btn_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_Login;
    private javax.swing.JCheckBox _chk_administration;
    private javax.swing.JCheckBox _chk_agent;
    private javax.swing.JLabel _lbl_Password;
    private javax.swing.JLabel _lbl_Username;
    private javax.swing.JTextField _txt_Password;
    private javax.swing.JTextField _txt_Username;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
