/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastas.UI;

/**
 *
 * @author Xelop
 */
public class ParticipantsMenu extends javax.swing.JFrame {

    /**
     * Creates new form ParticipantsMenu
     */
    public ParticipantsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Participants = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        _btn_BeginAuction = new javax.swing.JButton();
        _btn_RestartAuction = new javax.swing.JButton();
        _btn_Bid = new javax.swing.JButton();
        _btn_More = new javax.swing.JButton();
        _btn_CommentBuyer = new javax.swing.JButton();
        _btn_CommentSeller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Participants.setText("PARTICIPANTS");

        _btn_BeginAuction.setText("Start Auction");
        _btn_BeginAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_BeginAuctionActionPerformed(evt);
            }
        });

        _btn_RestartAuction.setText("Restart Auction");
        _btn_RestartAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_RestartAuctionActionPerformed(evt);
            }
        });

        _btn_Bid.setText("Bid");
        _btn_Bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_BidActionPerformed(evt);
            }
        });

        _btn_More.setText("More");
        _btn_More.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_MoreActionPerformed(evt);
            }
        });

        _btn_CommentBuyer.setText("Comment as Buyer");
        _btn_CommentBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_CommentBuyerActionPerformed(evt);
            }
        });

        _btn_CommentSeller.setText("Comment as Seller");
        _btn_CommentSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_CommentSellerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_btn_Bid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_btn_CommentBuyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_btn_RestartAuction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_btn_BeginAuction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_btn_More, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_btn_CommentSeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(_btn_BeginAuction)
                .addGap(18, 18, 18)
                .addComponent(_btn_RestartAuction)
                .addGap(18, 18, 18)
                .addComponent(_btn_Bid)
                .addGap(18, 18, 18)
                .addComponent(_btn_CommentBuyer)
                .addGap(18, 18, 18)
                .addComponent(_btn_CommentSeller)
                .addGap(18, 18, 18)
                .addComponent(_btn_More)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(_lbl_Participants))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(_lbl_Participants)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_MoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_MoreActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuAll(this).setVisible(true);
    }//GEN-LAST:event__btn_MoreActionPerformed

    private void _btn_BeginAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_BeginAuctionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CreateAuction(this,1,0).setVisible(true);
    }//GEN-LAST:event__btn_BeginAuctionActionPerformed

    private void _btn_RestartAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_RestartAuctionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ListAuctions(this,1,"","",0).setVisible(true);
    }//GEN-LAST:event__btn_RestartAuctionActionPerformed

    private void _btn_BidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_BidActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FindAuctions(this, 2).setVisible(true);
    }//GEN-LAST:event__btn_BidActionPerformed

    private void _btn_CommentBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_CommentBuyerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ListAuctions(this,7,"","",0).setVisible(true);
    }//GEN-LAST:event__btn_CommentBuyerActionPerformed

    private void _btn_CommentSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_CommentSellerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ListAuctions(this,8,"","",0).setVisible(true);
    }//GEN-LAST:event__btn_CommentSellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipantsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipantsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipantsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipantsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipantsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_BeginAuction;
    private javax.swing.JButton _btn_Bid;
    private javax.swing.JButton _btn_CommentBuyer;
    private javax.swing.JButton _btn_CommentSeller;
    private javax.swing.JButton _btn_More;
    private javax.swing.JButton _btn_RestartAuction;
    private javax.swing.JLabel _lbl_Participants;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
